-名称：设置Java JDK
  用途：actions/setup-java@v1.3.0
  与：
    ＃在路径上可用的Java版本。采用完整或完整的Java版本或1.x语法（例如1.8 => Java 8.x）
    Java版本： 
    ＃软件包类型（jre，jdk，jdk + fx）
    java-package：＃可选，默认为jdk
    ＃软件包的体系结构（x86，x64）。
    体系结构：＃可选，默认为x64
    ＃压缩JDK所在的路径。该路径可以在您的源存储库中，也可以在代理上的本地路径中。
    jdkFile：＃可选
    ＃pom.xml文件中distributionManagement存储库的ID。默认是`github`
    服务器ID：＃可选
    ＃环境变量名称，用于对Apache Maven存储库进行身份验证的用户名。默认值为$ GITHUB_ACTOR
    服务器用户名：＃可选
    ＃用于口令或令牌的环境变量名称，用于对Apache Maven存储库进行身份验证。默认值为$ GITHUB_TOKEN
    服务器密码：＃可选
    ＃写入settings.xml文件的路径。默认值为〜/ .m2。
    settings-path：＃可选
